### ISSUE TITLE
Nit: vestigial text

### ISSUE THREAD

**Issue by Ealdwulf** [bbriscoe/accecn#4]
Hi,
Looks like this line:
https://github.com/bbriscoe/accecn/blob/b6d85b8fbc5146a56dea55bd9702fe9314d87f64/draft-ietf-tcpm-accurate-ecn.xml#L393
contains a vestige from when this doc was experimental track.

**Comment by bbriscoe** [comment]
Thanks. Will fix.

**Comment by bbriscoe** [comment]
Note to self:
Also, when I updated the MPTCP ref from RFC6824 to RFC8684, I overlooked that I can no longer call it experimental.

**Comment by bbriscoe** [comment]
Done.
